routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TestCaseTNRController;
use App\Http\Controllers\TestCaseController;
use App\Http\Controllers\ExportAsCSVController;
use App\Http\Controllers\ImportCustomPropertiesFile;
use App\Http\Controllers\FareFamilyController;
use App\Http\Controllers\AncillariesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::post('export-as-csv', [ExportAsCSVController::class, 'export'])->name('export.as.csv');
Route::post('change-language', [HomeController::class, 'changeLang'])->name('change.lang');
Route::resource('import-custom-properties-file', ImportCustomPropertiesFile::class);
Route::resource('test-number', TestCaseController::class)->parameters(['test-number' => 'TestNumber']);
Route::post('delete-all-test-number', [TestCaseController::class, 'destroyAll'])->name('destroy.all.tn');
Route::resource('ancillaries-name', AncillariesController::class);
Route::resource('fare-family', FareFamilyController::class);
Route::resource('tnr', TestCaseTNRController::class)->parameters(["tnr" => "cid"]);
Route::post('delete-all-tnr', [TestCaseTNRController::class, 'destroyAll'])->name('destroy.all.tnr');

resources/views/layouts/navbar/navbar.blade.php
<aside class="left-sidebar">
    <div>
      <div class="brand-logo d-flex align-items-center justify-content-between">
        <a href="{{ route('index') }}" class="text-nowrap logo-img">
          <img src="{{ asset('assets/img/logos/logo_custom_properties-full-2.png') }}" width="180" style="margin-left:24%;margin-top:8%;width:65%;" alt="" />
        </a>
        <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
          <i class="ti ti-x fs-8"></i>
        </div>
      </div>
      <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
        <ul id="sidebarnav">
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Home</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-layout-dashboard"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['homepage'] }}</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Test Number</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('test-number.create') }}" aria-expanded="false">
              <span>
                <i class="ti ti-test-pipe"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['testNumber'] }}</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Ancillaries</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('ancillaries-name.create') }}" aria-expanded="false">
              <span>
                <i class="ti ti-luggage"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['ancillariesName'] }}</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">Fare Family</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('fare-family.create') }}" aria-expanded="false">
              <span>
                <i class="ti ti-flare"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['fareFamily'] }}</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">{{ __('Navbar')['automatedTestsTitle'] }}</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('tnr.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-test-pipe"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['automatedTests'] }}</span>
            </a>
          </li>
          <li class="nav-small-cap">
            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
            <span class="hide-menu">{{ __('Navbar')['fileImportTitle'] }}</span>
          </li>
          <li class="sidebar-item">
            <a class="sidebar-link" href="{{ route('import-custom-properties-file.index') }}" aria-expanded="false">
              <span>
                <i class="ti ti-file-upload"></i>
              </span>
              <span class="hide-menu">{{ __('Navbar')['fileImport'] }}</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </aside>

resources/views/layouts/navbar/topbar.blade.php
@php
    if (App::getLocale() == 'en') {
        Session::put('otherLang', 'fr');
        $langText = "FR";
    } else {
        Session::put('otherLang', 'en');
        $langText = "EN";
    }
@endphp

<header class="app-header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                    <i class="ti ti-menu-2"></i>
                </a>
            </li>
        </ul>
        <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                <li class="nav-item dropdown">
                    <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        <img src='{{ asset('assets/img/countryflag/' . Session::get('localeLang') . '.png') }}'
                            alt="{{ Session::get('localeLang') }} lang" width="35" height="35" class="rounded-circle">
                    </a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                        <div class="message-body">
                            <form method="POST" action="{{ route('change.lang', Session::get('otherLang')) }}">
                                @csrf
                                <input type="text" name="lang" value="{{ Session::get('otherLang') }}" hidden>
                                <button type="submit" class="d-flex align-items-center gap-2 dropdown-item">
                                    <img src='{{ asset('assets/img/countryflag/' . Session::get('otherLang') . '.png') }}'
                                        alt="{{ Session::get('otherLang') }} lang" width="35" height="35" class="rounded-circle">
                                    {{ $langText }}
                                </button>
                            </form>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>