routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\TestCaseTNRController;
use App\Http\Controllers\TestCaseController;
use App\Http\Controllers\ExportAsCSVController;
use App\Http\Controllers\ImportCustomPropertiesFile;
use App\Http\Controllers\FareFamilyController;
use App\Http\Controllers\AncillariesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::post('export-as-csv', [ExportAsCSVController::class, 'export'])->name('export.as.csv');
Route::post('change-language', [HomeController::class, 'changeLang'])->name('change.lang');
Route::resource('import-custom-properties-file', ImportCustomPropertiesFile::class);
Route::resource('test-number', TestCaseController::class)->parameters(['test-number' => 'TestNumber']);
Route::post('delete-all-test-number', [TestCaseController::class, 'destroyAll'])->name('destroy.all.tn');
Route::resource('ancillaries-name', AncillariesController::class);
Route::resource('fare-family', FareFamilyController::class);
Route::resource('tnr', TestCaseTNRController::class)->parameters(["tnr" => "cid"]);
Route::post('delete-all-tnr', [TestCaseTNRController::class, 'destroyAll'])->name('destroy.all.tnr');

app/Models/FareFamily.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FareFamily extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $table = 'farefamily';
    protected $primaryKey = 'id';
}

app/Http/Controllers/FareFamilyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\FareFamily;



class FareFamilyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('farefamily.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        FareFamily::firstOrCreate([
            'cabin_type' => $request->cabin_type_name,
            'fare_family_name' => $request->fare_family_name,
            'created_at' => now()
        ]);

        $messageTemplate = __('Controllers')['FareFamily']['Functions']['store'];
        $message = str_replace([":cabinType", ":fareFamily"], [$request->cabin_type_name, $request->fare_family_name], $messageTemplate);
        return redirect('/fare-family/create', 301)->with(compact('message'));
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $fareFamily = FareFamily::find($id);
        return view('farefamily.show', compact('fareFamily'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $fareFamily = FareFamily::find($id);
        $fareFamily->cabin_type = $request->cabin_type_name;
        $fareFamily->fare_family_name = $request->fare_family_name;
        $fareFamily->updated_at = now();
        $fareFamily->save();
        $messageTemplate = __('Controllers')['FareFamily']['Functions']['update'];
        $message = str_replace([":cabinType", ":fareFamily"], [$fareFamily->cabin_type, $fareFamily->fare_family_name], $messageTemplate);
        return redirect('/', 301)->with(compact('message'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $fareFamily = FareFamily::find($id);
        $messageTemplate = __('Controllers')['FareFamily']['Functions']['destroy'];
        $message = str_replace([":cabinType", ":fareFamily"], [$fareFamily->cabin_type, $fareFamily->fare_family_name], $messageTemplate);
        $fareFamily->delete();
        return redirect('/', 301)->with(compact('message'));
    }
}

resources/views/farefamily/create.blade.php
@extends('layouts.master')
@section('title', "| " . __('PageTitle')['faremilyTitle'])
@section('header-scripts')
@endsection

@section('content')

    @if ($message = Session::get('message'))
        <div class="alert alert-success" role="alert">
            {{ $message }}
        </div>
    @elseif($message = Session::get('error'))
        <div class="alert alert-error" role="alert">
           {{ $message }}
        </div>
    @endif

    <div class="row">
        <div class="col-lg-10">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">{{ __('FareFamilyPage')['fareFamilyFormCreateTitle'] }}</h5>
                    <form method="POST" class="forms-sample" action="{{ route('fare-family.store') }}">
                        @csrf
                        <div class="mb-3">
                            <label for="cabin_type_name" class="form-label">{{ __('FareFamilyPage')['fareFamilyFormCabinTypeTitle'] }}</label>
                            <select id="cabin_type_name" name="cabin_type_name" class="form-select">
                                <option>{{ __('FareFamilyPage')['fareFamilyFormCabinTypeNamePlaceholder'] }}</option>
                                <option>ECONOMY</option>
                                <option>PREMIUM</option>
                                <option>BUSINESS</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="fare_family_name" class="form-label">{{ __('FareFamilyPage')['fareFamilyFormInputName'] }}</label>
                            <input type="text" class="form-control" id="fare_family_name" name="fare_family_name">
                        </div>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            <div id="sticky-div" style="position: fixed;">
                <div class="card">
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">{{ __('FormButton')['formCreateButtonText'] }}</button>
                        </form><hr>
                        <a href="{{ route('index') }}" class="btn btn-danger">{{ __('FormButton')['formCancelButtonText'] }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('footer-scripts')
    <script>
        // Cache selectors outside callback for performance. 
        var $window = $(window),
            $stickyEl = $('#sticky-div'),
            elTop = $stickyEl.offset().top;

        $window.scroll(function() {
            $stickyEl.toggleClass('sticky', $window.scrollTop() > elTop);
        });
    </script>
@endsection

resources/views/farefamily/show.blade.php
@extends('layouts.master')
@section('title', "| " . __('PageTitle')['faremilyTitleEdit']. " : $fareFamily->cabin_type $fareFamily->fare_family_name")
@section('header-scripts')
@endsection
@section('content')

    @if ($message = Session::get('message'))
        <div class="alert alert-success" role="alert">
            {{ $message }}
        </div>
    @elseif($message = Session::get('error'))
        <div class="alert alert-error" role="alert">
           {{ $message }}
        </div>
    @endif

    <div class="row">
        <div class="col-lg-10">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Ajouter une fare family</h5>
                    <form method="POST" class="forms-sample" action="{{ route('fare-family.update', $fareFamily->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="cabin_type_name" class="form-label">Type de cabine</label>
                            <select id="cabin_type_name" name="cabin_type_name" class="form-select">
                                @if ($fareFamily->cabin_type)
                                    <option>{{ $fareFamily->cabin_type }}</option>
                                    <option>------------</option>
                                @endif
                                <option disabled>Sélectionner une cabine</option>
                                <option>ECONOMY</option>
                                <option>PREMIUM</option>
                                <option>BUSINESS</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="fare_family_name" class="form-label">Nom de la fare family</label>
                            <input type="text" class="form-control" id="fare_family_name" name="fare_family_name" value="{{ $fareFamily->fare_family_name }}">
                        </div>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            <div id="sticky-div" style="position: fixed;">
                <div class="card">
                    <div class="card-body">
                        <button type="submit" class="btn btn-primary">{{ __('FormButton')['formEditButtonText'] }}</button>
                        </form><hr>
                        <a href="{{ route('index') }}" class="btn btn-danger">{{ __('FormButton')['formCancelButtonText'] }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('footer-scripts')
    <script>
        // Cache selectors outside callback for performance. 
        var $window = $(window),
            $stickyEl = $('#sticky-div'),
            elTop = $stickyEl.offset().top;

        $window.scroll(function() {
            $stickyEl.toggleClass('sticky', $window.scrollTop() > elTop);
        });
    </script>
@endsection